version: 2.1

orbs:
  docker: circleci/docker@0.5.20

use-docker-executor: &use-docker-executor
  executor:
    name: docker/docker

jobs:
  test:
    <<: *use-docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - docker/build:
          step-name: Build Test CI image
          image: test_ci
          tag: latest
          extra_build_args: --target ci
      - run:
          name: Lint
          command: docker-compose run test_ci yarn lint
      - run:
          name: Tests
          command: docker-compose run test_ci yarn test:ci

workflows:
  version: 2
  lint-and-test:
    jobs:
      - test
